apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-k8s-monitoring.fullname" . }}-frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
  type: ClusterIP