{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devops-k8s-monitoring.fullname" . }}-ingress
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "devops-k8s-monitoring.fullname" . }}-frontend
                port:
                  number: {{ .Values.service.frontend.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "devops-k8s-monitoring.fullname" . }}-backend
                port:
                  number: {{ .Values.service.backend.port }}
{{- end -}}